### ISSUE TITLE
About Multiple GPUs Running GraphGPS in Parallel

### ISSUE THREAD

**Issue by Ranceeeee** [rampasek/GraphGPS#13]
Hello GraphGPS team, have you tried to run GraphGPS with multiple GPUs? If you have tried, what is the specific operation mode? Thank you.

**Comment by rampasek** [comment]
Hi @Ranceeeee, unfortunately I have not run GraphGPS in a multiple GPU setting. The latest [PyG release 2.1.0](https://github.com/pyg-team/pytorch_geometric/releases/tag/2.1.0) has brought PyTorch Lightning support for GraphGym, upgrading to which in the future may be one of the easier ways to enable multiple GPU regime.
