### ISSUE TITLE
Configuration Training options 

### ISSUE THREAD

**Issue by MohamedEldafrawi2** [rampasek/GraphGPS#18]
In the Configuration training options, there is no attribute called mode. However, you added this attribute to the configuration files 
training:
mode: custom

**Comment by rampasek** [comment]
Hi Mohamed,

I believe that is because you are trying to run it with PyGv2.1 instead of PyGv2.0.4. I will update the PyG compatibly in the next ~2 weeks after PyGv2.2 is released.

Best,
Ladislav

**Comment by MohamedEldafrawi2** [comment]
Thank you!
