### ISSUE TITLE
Question about maxfreqs

### ISSUE THREAD

**Issue by chendiqian** [rampasek/GraphGPS#30]
Dear contributors,
I wonder why you use max_freqs = 1 in e.g. https://github.com/rampasek/GraphGPS/blob/main/configs/GPS/zinc-GPS-LapPE%2BRWSE.yaml#L26
Because the eigvec corresponding to the least eigval is ones. So the nodes are indistinguishable with only 1 element of eigvec..

**Comment by rampasek** [comment]
Hi,

You are right, setting it to `max_freqs = 1` effectively means no meaningful Laplacian PE is used.
Unfortunately I don't exactly remember how this was selected, I believe I run a grid search and found that adding LapPE in addition to RWSE to the input didn't improve performance so it was left with the `max_freqs = 1`.

Apologies for the late answer!
