### ISSUE TITLE
Implementing on our custom dataset

### ISSUE THREAD

**Issue by afshinebtia** [rampasek/GraphGPS#31]
Hello,
First, Thanks for your great work.
Would you please elaborate more that how can I use the functionalities of this project on my attributed graphs?

Thanks

**Comment by rampasek** [comment]
Hi,
Apologies for a late reply! A good starting point to how to add a new dataset is to see my answer to issue #3 (https://github.com/rampasek/GraphGPS/issues/3) and follow the existing dataset examples.
