### ISSUE TITLE
Feature Request: Caching of Precomputed Encodings

### ISSUE THREAD

**Issue by kaansancak** [rampasek/GraphGPS#32]
Hello,

Thank you for the excellent work! I wanted to inquire if there are any plans to implement saving/caching of the preprocessed graph. When working with new models, the pre-computation step can be quite cumbersome and time-consuming.

**Comment by rampasek** [comment]
Hi,
Apologies for a late reply. Unfortunately I no longer develop or actively maintain this code base. Perhaps have a look at https://github.com/datamol-io/graphium 
Best,
Ladislav
