### ISSUE TITLE
Implementation on custom dataset

### ISSUE THREAD

**Issue by borismartirosyandenovo** [rampasek/GraphGPS#33]
Thank you for good architecture, but I cannot implement this in our own dataset, is there any possibility to do that?

**Comment by rampasek** [comment]
Hi,
Apologies for a late reply! A good starting point to how to add a new dataset is to see my answer to issue https://github.com/rampasek/GraphGPS/issues/3 and follow the existing dataset examples. You can also have a look at https://github.com/datamol-io/graphium which is a new maintained project that has GPS(++) implementation.
