### ISSUE TITLE
Is there a vanilla implementation without graphgym

### ISSUE THREAD

**Issue by shubhamguptaiitd** [rampasek/GraphGPS#36]
Use of graphgym has made it very difficult to change and understand code. Does there exist an vanilla implementation without use of graphgym

**Comment by migalkin** [comment]
The reference implementation is here in this repo. 
Alternatively, you might want to have a look at the re-implementation [GPSConv](https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.GPSConv.html) layer in PyG and its basic [tutorial](https://github.com/pyg-team/pytorch_geometric/blob/master/examples/graph_gps.py) on using GPS
