### ISSUE TITLE
How to implement graphgps to node classification

### ISSUE THREAD

**Issue by OswaldoBornemann** [rampasek/GraphGPS#37]
How to implement graphGPS to node classification? Is there any example?

**Comment by migalkin** [comment]
There is a handful of example node classification configs, eg, for WebKB ones like here https://github.com/rampasek/GraphGPS/blob/main/configs/GPS/webkb-tex-GPS.yaml

**Comment by OswaldoBornemann** [comment]
> There is a handful of example node classification configs, eg, for WebKB ones like here https://github.com/rampasek/GraphGPS/blob/main/configs/GPS/webkb-tex-GPS.yaml

Thank you so much.
