### ISSUE TITLE
Test ACC for PPA dataset

### ISSUE THREAD

**Issue by haoyuhan1** [rampasek/GraphGPS#47]
Hi,

I tried train the GPS on ppa dataset by using configs/GPS/ogbg-ppa-GPS.yaml. I found the training acc can be near 100%, but the val and test acc are very low, near 1%. The enviroments are the same with Readme file. Is there any potential issues? Thank you!

**Comment by migalkin** [comment]
How long did you train the model for? Can it be the same as the issue #14? If you check the published logs, there is some sort of a "grokking" happening around 160-180 epochs after which test accuracy quickly grows to 80%-ish

**Comment by haoyuhan1** [comment]
Yes, I found there is a performance boost after 180 epochs. Thank you!
