### ISSUE TITLE
Results on PATTERN

### ISSUE THREAD

**Issue by MatthewCYM** [rampasek/GraphGPS#8]
Hi,

Thank you for your impressive work. I try to reproduce the results of SAN and GatedGCN on PATTERN using GraphGPS framework. The results are all around 89.9 test accuracy, which are significantly higher than the results reported in the paper (~85.6 test accuracy).

I understand that you report the results from benchmarking gnn. May I ask if you have encountered same issue during the experiments?

The config file I use is in [config.zip](https://github.com/rampasek/GraphGPS/files/9315786/config.zip)

Thank you!

Yiming

**Comment by rampasek** [comment]
Hi @MatthewCYM,

Thank you for bringing this up and sorry for the delay. I found that there was a mistake in GraphGPS evaluation, I used plain accuracy as the evaluation metric, and not the weighted accuracy. I have now fixed the code and redone the GPS experiments, please see #12 .

Best,
Ladislav
